# Generated by Django 3.1.2 on 2021-03-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='types',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('secretaire', 'Secretaire'), ('super_user', 'Super_user')], default='etudiant', max_length=20),
        ),
    ]
