# Generated by Django 3.1.2 on 2021-03-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='types',
        ),
    ]
