version: '3.9'
services:
  csdwebsite:
    container_name: csdwebsite
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 7000:7000
    depends_on:
      - dbcsdwebsite

  dbcsdwebsite:
    container_name: mysqlcsdwebsite
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
    volumes:
      - /./dbcsdwebsitedata/var/lib/mysql
   
    